apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: demo-connect-cluster
spec:
  version: 2.3.0
  replicas: 1
  bootstrapServers: demo-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
  config:
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1